language: node_js

node_js:
  - 0.6
  - 0.8
  - 0.9

matrix:
  allow_failures:
    - node_js: 0.9

parallelized_test: true

install:
  - npm install
  - cd ./test
  - npm install
  - cd ../

script:
  - npm test

after_script:
  - null

# build_image: shippable/minv2

notifications:
  email:
    on_failure: 'always'
    on_success: 'always'
    recipients:
      - "rolandpoulter@gmail.com"
